name: Verify

on:
  # Trigger the workflow on push or pull request on master branch
  pull_request:
    branches:
    - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up qemu
      uses: docker/setup-qemu-action@v1
      with:
        platforms: all

    - name: Print environment
      run: |
        uname -a
        docker --version

    - name: Build & test linux/amd64 image
      run: make images test

    - name: Build linux/amd64 images and binaries
      run: make clean singlearch-tar
